function DemoText()
msg1  =  ['Welcome to the experiment.\n\n\n\nPress SPACE to continue. '];

% msg2  = ['In this study, you will see a vertical occluder and a fixation point in the center of the screen. \n \n'...
%     'It is important that you keep your eye gaze fixated at the fixation point throughout the entire session.'...
%     '\n \n \n \n Press SPACE to see a demonstration.'];

% msg3 = ['\n \n On each trial, you will see a line segment appearing on each side of the occluder for a short'...
%     '\n \n amount of time. The occluder will always be covering parts of the line segments. \n \n \n \n Press SPACE to see a demonstration.'];

msg4 = ['HEIGHT JUDGEMENT task: judge which line segment is HIGHER than the other. \n\n'...
    'Press a BLUE key on the LEFT if the line on the LEFT is higher \n\n '...
    'Press a BLUE key on the RIGHT if the line on the RIGHT is higher. \n\n' ...
    'Please press the key that reflects your confidence about your judgement:\n\n'...
    '1 = not confident; 2 = moderately confident; 3 = confident; 4 = very confident;'...
    '\n \n \n \n Press SPACE to see a demonstration.'];



msg5 = ['SAMENESS JUDGEMENT task: judge whether the two line segments belong to the SAME line.\n\n'...
    'Press a RED key on the LEFT if the lines are the SAME line \n\n '...
    'Press a RED key on the RIGHT if the lines are DIFFERENT lines. \n\n' ...
    'Please press the key that reflects your confidence about your judgement:\n\n'...
    '1 = not confident; 2 = moderately confident; 3 = confident; 4 = very confident;\n\n\n'...
    '\n \n \n \n Press SPACE to see a demonstration.'];


% In this experiments the lines will appear at four different heights on the
% screen. On each trial the lines are randomly chosen from near one of the 
% heights.
msg6 = ['Line segments will show up around 4 different levels on the occluder. \n\n\n\nPress SPACE to see a demonstration.'];
    
%msg7 = ['The position of the line segment on each side of the occluder relative to the level will \n\n be drawn from a normal distribution with a mean of zero.'...
%    'This means that the probability \n \n for a certain distance from the level to show up increase as it approaches zero. \n \n \n \n Press SPACE to see a demonstration.'];

msg8 = ['Press SPACE to see an example of possible trials around this level.'];

msg9 = ['On each trial the lines are randomly chosen from near one of the heights. \n\nPress SPACE to see an example of possible trials.'];

msg10 = ['In the SAMENESS JUDGEMENT task, line segments in half of the trials belong to the same lines. \n\nOn the other half of the trials, line segments belong to different lines. \n\n Each trial is generated randomly.'];

save('CE_demo_text')
end